### ISSUE TITLE
Can't build image Hadoop-Base not fount

### ISSUE THREAD

**Issue by veveno** [martinkarlssonio/big-data-solution#1]
Hello i try to deploy this app but when i run the master-build.sh, the script block at 

<<Step 1/9 : FROM hadoop-base
pull access denied for hadoop-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied>>

i have try docker login and the login success

i have search the image in docker hub but this image doesn't exist, do you have an existing image ?

**Comment by martinkarlssonio** [comment]
Hello! If you check the script, master-build.sh, you can see that it navigates in to the folders and build 'hadoop-base' image.
The issue you have copy-pasted indicate that this hasn't been executed successfully.
