### ISSUE TITLE
hadoop-base build error

### ISSUE THREAD

**Issue by LarsHilden** [martinkarlssonio/big-data-solution#3]
There is a build error in hadoop-base, probably due to changes in the repo paths.:

cd hadoop/base && docker build . -t hadoop-base && cd ../..
Sending build context to Docker daemon  10.75kB
Step 1/3 : FROM debian:9
 ---> 662c05203bab
Step 2/3 : COPY test.py /
 ---> Using cache
 ---> f3eae3651d7f
Step 3/3 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends       openjdk-8-jdk       net-tools       curl       netcat       gnupg       libsnappy-dev       nano       wget     && rm -rf /var/lib/apt/lists/*
 ---> Running in b8744405cfc4
Ign:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://security.debian.org/debian-security stretch/updates Release
Ign:3 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:4 http://deb.debian.org/debian stretch InRelease
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:3 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:6 http://deb.debian.org/debian stretch-updates InRelease
Ign:3 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:7 http://deb.debian.org/debian stretch Release
Ign:3 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:3 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
Ign:8 http://deb.debian.org/debian stretch-updates Release
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Err:3 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
  404  Not Found [IP: 151.101.2.132 80]
Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
Ign:10 http://deb.debian.org/debian stretch/main all Packages
Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
Ign:10 http://deb.debian.org/debian stretch/main all Packages
Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
Ign:10 http://deb.debian.org/debian stretch/main all Packages
Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
Ign:10 http://deb.debian.org/debian stretch/main all Packages
Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
Ign:10 http://deb.debian.org/debian stretch/main all Packages
Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Err:9 http://deb.debian.org/debian stretch/main amd64 Packages
  404  Not Found
Ign:10 http://deb.debian.org/debian stretch/main all Packages
Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
  404  Not Found
Reading package lists...
W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.2.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends       openjdk-8-jdk       net-tools       curl       netcat       gnupg       libsnappy-dev       nano       wget     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by abralock** [comment]
Try this... https://github.com/abralock/big-data-solution/commits/develop on the hadoop/base/Dockerfile

**Comment by abrahamlock** [comment]
Yes, the Debian package moved to Archive. But I'm able to bring it up using the code that you reverted.
