### ISSUE TITLE
Different Errors

### ISSUE THREAD

**Issue by JulianV25** [martinkarlssonio/big-data-solution#6]
I have following Errors when trying it: 
Error response from daemon: network with name bds-network already exists
[+] Building 1.8s (7/23)                                         docker:default
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 1.90kB                                     0.0s
 => [internal] load metadata for docker.io/library/debian:9                1.0s
 => [ 1/19] FROM docker.io/library/debian:9@sha256:c5c5200ff1e9c73ffbf188  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 62B                                           0.0s
 => CACHED [ 2/19] COPY test.py /                                          0.0s
 => ERROR [ 3/19] RUN apt-get update && DEBIAN_FRONTEND=noninteractive ap  0.8s
------                                                                          
 > [ 3/19] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends       openjdk-8-jdk       net-tools       curl       netcat       gnupg       libsnappy-dev       nano       wget     && rm -rf /var/lib/apt/lists/*:                                                                
0.305 Ign:1 http://security.debian.org/debian-security stretch/updates InRelease
0.308 Ign:2 http://deb.debian.org/debian stretch InRelease
0.319 Ign:3 http://security.debian.org/debian-security stretch/updates Release
0.324 Ign:4 http://deb.debian.org/debian stretch-updates InRelease
0.332 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
0.347 Ign:6 http://deb.debian.org/debian stretch Release
0.347 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.361 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
0.362 Ign:8 http://deb.debian.org/debian stretch-updates Release
0.378 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.382 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.393 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.399 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
0.410 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.413 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.425 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.428 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
0.440 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.442 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.456 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
0.457 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.471 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.472 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.486 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.489 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
0.500 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.503 Err:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.503   404  Not Found [IP: 151.101.194.132 80]
0.517 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.531 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.546 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.559 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.573 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.587 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.601 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.615 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.629 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.642 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.656 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.670 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.684 Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.684   404  Not Found
0.697 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.714 Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.714   404  Not Found
0.718 Reading package lists...
0.723 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
0.723 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
0.723 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
0.723 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.194.132 80]
0.723 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
0.723 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
0.723 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
Dockerfile:6
--------------------
   5 |     
   6 | >>> RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
   7 | >>>       openjdk-8-jdk \
   8 | >>>       net-tools \
   9 | >>>       curl \
  10 | >>>       netcat \
  11 | >>>       gnupg \
  12 | >>>       libsnappy-dev \
  13 | >>>       nano \
  14 | >>>       wget \
  15 | >>>     && rm -rf /var/lib/apt/lists/*
  16 |     RUN apt-get update && apt-get upgrade -y
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends       openjdk-8-jdk       net-tools       curl       netcat       gnupg       libsnappy-dev       nano       wget     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
master-build.sh: line 6: cd: spark/base: No such file or directory
[+] Building 0.9s (17/17) FINISHED                                              
 => [spark-master internal] load build definition from Dockerfile          0.0s
 => => transferring dockerfile: 198B                                       0.0s
 => [spark-master internal] load .dockerignore                             0.0s
 => => transferring context: 2B                                            0.0s
 => CANCELED [spark-master internal] load metadata for docker.io/library/  0.9s
 => [hadoop-datanode internal] load build definition from Dockerfile       0.0s
 => => transferring dockerfile: 301B                                       0.0s
 => [hadoop-datanode internal] load .dockerignore                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [hadoop-datanode internal] load metadata for docker.io/library/  0.9s
 => [hadoop-namenode internal] load build definition from Dockerfile       0.0s
 => => transferring dockerfile: 301B                                       0.0s
 => [hadoop-namenode internal] load .dockerignore                          0.0s
 => => transferring context: 2B                                            0.0s
 => [jupyter-notebook internal] load build definition from Dockerfile      0.0s
 => => transferring dockerfile: 1.90kB                                     0.0s
 => [jupyter-notebook internal] load .dockerignore                         0.0s
 => => transferring context: 2B                                            0.0s
 => CANCELED [jupyter-notebook internal] load metadata for docker.io/libr  0.9s
 => [hadoop-nodemanager-1 internal] load .dockerignore                     0.0s
 => => transferring context: 2B                                            0.0s
 => [hadoop-nodemanager-1 internal] load build definition from Dockerfile  0.0s
 => => transferring dockerfile: 186B                                       0.0s
 => [hadoop-resourcemanager internal] load build definition from Dockerfi  0.0s
 => => transferring dockerfile: 186B                                       0.0s
 => [hadoop-resourcemanager internal] load .dockerignore                   0.0s
 => => transferring context: 2B                                            0.0s
 => [hadoop-historyserver internal] load build definition from Dockerfile  0.0s
 => => transferring dockerfile: 343B                                       0.0s
 => [hadoop-historyserver internal] load .dockerignore                     0.0s
 => => transferring context: 2B                                            0.0s
------
 > [hadoop-datanode internal] load metadata for docker.io/library/hadoop-base:latest:
------
failed to solve: hadoop-base: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

Dockers are new to me so I appreciate every help i can get. Thank you

**Comment by qipsys** [comment]
i fork this repo and make some changes, with it docker created fine https://github.com/qipsys/big-data-solution
